# Tensors

In [2]:
import tensorflow as tf

2024-12-09 15:58:06.497901: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-09 15:58:06.499679: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-09 15:58:06.550263: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-09 15:58:06.754577: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-09 15:58:11.937424: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF

## Rank and shape

### Rank 1

Define an 1-rank tensor of four integers

![](images/rank1.png)

In [36]:
t1=tf.constant([ 7, 2, 9, 10])
t1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  2,  9, 10], dtype=int32)>

Check tensor rank

In [42]:
tf.rank(t1).numpy()

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Access tensor content:

In [41]:
t1[1].numpy()

2

### Rank 2

Define an 2-rank tensor of four integers

![](images/rank2.png)


In [6]:
t2=tf.constant([ [5.1, 3.0, 4.5],  [9.1, 0.1, 0.3] ] )
t2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5.1, 3. , 4.5],
       [9.1, 0.1, 0.3]], dtype=float32)>

Access tensor content:

In [7]:
t2[0,2]

<tf.Tensor: shape=(), dtype=float32, numpy=4.5>

### Rank 3

Define an 3-rank tensor of four integers

In [8]:
t3=tf.constant([[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]], ] )
t3

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

Access tensor content:

In [9]:
t3[2,1,0]

<tf.Tensor: shape=(), dtype=int32, numpy=25>

### Rank 0

Rank 0 tensor are not exactly like rank 1 tensor with shape(1).

In [10]:
t0=tf.constant(7)
t0

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
tf.rank(t0).numpy()

0

## Recap

|Definition|Shape|Rank|Access|Pitcure|
| --- | --- | --- |--- |--- |
| 23 | () | 0 | 23 |
| [ 7, 2, 9, 10]       | (4,)  |    1 | T[1]==2   | ![](images/rank1.png) |
| [ [5.1, 3.0, 4.5], <br>&nbsp;&nbsp;[9.1, 0.1, 0.3] ]   | (2,3) |    2 | T[0,2]==4.5   | ![](images/rank2.png) |
| [[[  1,   2], <br>&nbsp;&nbsp; [  4,   3], <br>&nbsp;&nbsp; [  7,   4]], <br>&nbsp;&nbsp;<br>&nbsp;&nbsp;[[  2, 100],<br>&nbsp;&nbsp; [  9, 100],<br>&nbsp;&nbsp;&nbsp;[  7,   5]],<br>&nbsp;&nbsp;<br>&nbsp;&nbsp;[[  1, 100],<br>&nbsp;&nbsp;&nbsp;&nbsp;[  3, 100],<br>&nbsp;&nbsp;&nbsp;&nbsp;[  0,   2]],<br>&nbsp;&nbsp;<br>&nbsp;&nbsp;[[  9, 100],<br>&nbsp;&nbsp;&nbsp;&nbsp;[  6, 100],<br>&nbsp;&nbsp;&nbsp;&nbsp;[  9,   8]]]                                                       | (4,3,2) | 3 |  T(0,2,1]==4 | ![](images/tensor-exercise1.png) |

### Exercise

#1 Let's check shape and rank of a zero axis tensor.

In [12]:
t0=tf.constant(23)
print(t0)
tf.rank(t0).numpy()

tf.Tensor(23, shape=(), dtype=int32)


0

#2 Now guess shape and rank of next tensor

In [13]:
tf.constant([[[1,7],[2,8],[3,9]], [[1,7], [2,8], [3,9]] ])

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 7],
        [2, 8],
        [3, 9]],

       [[1, 7],
        [2, 8],
        [3, 9]]], dtype=int32)>

Declare the tensor draw in pitcure:
![](images/tensor-exercise1.png)

In [14]:
xx=tf.constant([[[1,2], [4,3], [7,4]], [[2,100], [9,100], [7,5] ],   [[1,100], [3, 100], [0, 2]],   [[9,100], [6, 100], [9, 8]]])

In [15]:
xx[0,2,1]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## Slicing and reductions

### Reduction

Please note that every time we accessed a tensor entiy, we get a new tensor in return.

In [16]:
t2[0,2]

<tf.Tensor: shape=(), dtype=float32, numpy=4.5>

In fact, we get a slice of the orginal tensor. Practise with a 2-rank tensor

In [17]:
t2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5.1, 3. , 4.5],
       [9.1, 0.1, 0.3]], dtype=float32)>

Retreive the first row.

In [18]:
t2[0,:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5.1, 3. , 4.5], dtype=float32)>

Or the second column.

In [19]:
t2[:,1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3. , 0.1], dtype=float32)>

Or last column.

In [20]:
t2[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 0.3], dtype=float32)>

Or  range of columns: please, note that the end index is excluded.

In [21]:
t2[:,0:1]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[5.1],
       [9.1]], dtype=float32)>

In [22]:
t2[:,0:2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5.1, 3. ],
       [9.1, 0.1]], dtype=float32)>

In [23]:
t2[:,0:3]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5.1, 3. , 4.5],
       [9.1, 0.1, 0.3]], dtype=float32)>

Or, the same, take all columns from 2 to the end.

In [24]:
t2[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3. , 4.5],
       [0.1, 0.3]], dtype=float32)>

### Reductions

Let's practise on t2 again.

In [25]:
t2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5.1, 3. , 4.5],
       [9.1, 0.1, 0.3]], dtype=float32)>

Reduce on all axis taking the max value.

In [26]:
tf.reduce_max(t2)

<tf.Tensor: shape=(), dtype=float32, numpy=9.1>

Reduce on first axis (row) taking the max value.

In [27]:
tf.reduce_max(t2,0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([9.1, 3. , 4.5], dtype=float32)>

Reduce on second axis (column) taking the max value.

In [28]:
tf.reduce_max(t2,1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.1, 9.1], dtype=float32)>

Reduce on first axis (row) still keeping axis.

In [29]:
tf.reduce_max(t2,0, keepdims=True)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[9.1, 3. , 4.5]], dtype=float32)>

### Ragged and sparse


A ragged tensor simply has differen,,,

In [30]:
r=tf.ragged.constant([[1, 2, 3], [4,5]])
r

<tf.RaggedTensor [[1, 2, 3], [4, 5]]>

The shape presents not None values only for same length axis.

In [31]:
r.shape

TensorShape([2, None])

In [32]:
r[0,:], r[1,:]

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>)

# Logistical functions

Sigmoid

In [33]:
x=tf.constant([ -1, 0, 1, 2], dtype=float)
tf.keras.activations.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.26894143, 0.5       , 0.7310586 , 0.8807971 ], dtype=float32)>

Sofmax

In [34]:
tf.keras.activations.softmax(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.0320586 , 0.08714432, 0.23688284, 0.6439142 ], dtype=float32)>

Relu

In [35]:
tf.keras.activations.relu(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 1., 2.], dtype=float32)>